# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep

# Use vi keybinds
bindkey -v

# Enable auto correction
setopt correct

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/djaysky/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Download Znap, if it's not there yet.
[[ -r ~/Sources/znap/znap.zsh ]] ||
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ~/Sources/znap
source ~/Sources/znap/znap.zsh  # Start Znap

# Download zsh-autocomplete if it doesn't exist
[[ -r ~/Sources/zsh-autocomplete/zsh-autocomplete.plugin.zsh ]] ||
	git clone --depth 1 -- \
		https://github.com/marlonrichert/zsh-autocomplete ~/Sources/zsh-autocomplete
source ~/Sources/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# custom prompt
PS1='%~ > '

export TERMINAL="urxvt"
export EDITOR="vim"

# reminder to use ctrl+l instead of typing "clear"
alias clear='echo Just use ctrl+L && echo'

# open batstat
alias bat='batstat'

# terminal bluetooth manager
alias bt='bluetoothctl'

# copying files to the clipboard from the command line
alias clip='xclip -sel c < '

# reset terminal state - useful when using/making curses based apps
# I always accidentially type "rest" instead of "reset", so I added
# autocorrect
alias rest='reset'

# kill background processes
alias killbg='kill -9 `jobs -ps`'

# get the line count of files
alias len='wc -l'

# rename URXVT / terminal window
alias ren='printf "\033]0;%s\007"'

# update system - like the "xi" utility from the "xtools" package,
# but for updating instead of installing new packages
alias xu='sudo xbps-install -Su'

alias ff='fastfetch'
alias pico8='~/Apps/PICO8/pico8 &'
alias nano='nano -Ynone'

alias i3lock='i3lock  --indicator --verif-text="" --pass-media --time-color=99999999 --date-color=99999999 --time-str="%H:%M" --date-str="%m/%d/%Y" --wrong-text="" -k --blur 10'

alias bolt='nohup dbus-run-session flatpak run com.adamcake.Bolt & disown %1 && exit'
alias zandronum='flatpak run --filesystem=home --filesystem=host com.zandronum.Zandronum & disown %1 && exit'
alias fightcade='nohup dbus-run-session flatpak run --filesystem=home com.fightcade.Fightcade & disown %1 && exit'

alias doom='dsda-doom -iwad ~/Documents/doom-maps/iwads/doom.wad & disown %1 && exit'
alias doom2='dsda-doom -iwad ~/Documents/doom-maps/iwads/doom2.wad & disown %1 && exit'
alias heretic='dsda-doom -iwad ~/Documents/doom-maps/iwads/heretic.wad -heretic & disown %1 && exit'
alias strife='chocolate-strife -iwad ~/Documents/doom-maps/iwads/strife1.wad -file ~/Documents/doom-maps/iwads/voices.wad & disown %1 && exit'

alias 1password='nohup dbus-run-session flatpak run com.onepassword.OnePassword & disown %1 && exit'
alias discord='nohup dbus-run-session flatpak run com.discordapp.Discord & disown %1 && exit'
#alias steam='nohup dbus-run-session flatpak run com.valvesoftware.Steam & disown %1 && exit'
alias steam='steam & disown %1 && exit'
alias vinegar='nohup dbus-run-session flatpak run org.vinegarhq.Vinegar & disown %1 && exit'

export PATH="$PATH:/home/djaysky/.local/bin"
